package world

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// Parity: the Go enrichment MUST agree with the TypeScript implementation it
// replaces, or moving the work server-side would silently change what every
// user sees. testdata/enrich_golden.json is generated by EVALUATING the real
// frontend classifier/geo-index (not transcribed) over an exhaustive corpus:
// every keyword in every tier, both variants, every geo-hub keyword, every
// exclusion, plus adversarial word-boundary cases ("war" must not match
// "wardrobe"). Any drift fails here.

type goldenCase struct {
	Title string               `json:"title"`
	Full  ThreatClassification `json:"full"`
	Tech  ThreatClassification `json:"tech"`
	Geo   []GeoMatch           `json:"geo"`
}

func loadGolden(t *testing.T) []goldenCase {
	t.Helper()
	b, err := os.ReadFile("testdata/enrich_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var g struct {
		Cases []goldenCase `json:"cases"`
	}
	if err := json.Unmarshal(b, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(g.Cases) < 400 {
		t.Fatalf("golden corpus too small (%d) — regenerate it", len(g.Cases))
	}
	return g.Cases
}

func sameClass(a, b ThreatClassification) bool {
	return a.Level == b.Level && a.Category == b.Category &&
		a.Source == b.Source && math.Abs(a.Confidence-b.Confidence) < 1e-9
}

func TestClassifyByKeywordMatchesTypeScript(t *testing.T) {
	cases := loadGolden(t)
	bad := 0
	for _, c := range cases {
		for _, v := range []struct {
			variant string
			want    ThreatClassification
		}{{"full", c.Full}, {"tech", c.Tech}} {
			got := ClassifyByKeyword(c.Title, v.variant)
			if !sameClass(got, v.want) {
				bad++
				if bad <= 10 {
					t.Errorf("classify(%q, %s)\n  got  %+v\n  want %+v", c.Title, v.variant, got, v.want)
				}
			}
		}
	}
	if bad > 0 {
		t.Fatalf("%d/%d classifications diverge from the TypeScript source of truth", bad, len(cases)*2)
	}
	t.Logf("parity: %d titles × 2 variants identical to TypeScript", len(cases))
}

func TestInferGeoHubsMatchesTypeScript(t *testing.T) {
	cases := loadGolden(t)
	bad, withGeo := 0, 0
	for _, c := range cases {
		got := InferGeoHubs(c.Title)
		if len(c.Geo) > 0 {
			withGeo++
		}
		if len(got) != len(c.Geo) {
			bad++
			if bad <= 10 {
				t.Errorf("geo(%q): got %d matches, want %d", c.Title, len(got), len(c.Geo))
			}
			continue
		}
		for i := range got {
			w := c.Geo[i]
			if got[i].HubID != w.HubID || got[i].MatchedKeyword != w.MatchedKeyword ||
				math.Abs(got[i].Confidence-w.Confidence) > 1e-9 {
				bad++
				if bad <= 10 {
					t.Errorf("geo(%q)[%d]\n  got  %+v\n  want %+v", c.Title, i, got[i], w)
				}
				break
			}
		}
	}
	if bad > 0 {
		t.Fatalf("%d/%d geo inferences diverge from the TypeScript source of truth", bad, len(cases))
	}
	t.Logf("parity: %d titles identical to TypeScript (%d carry geo matches)", len(cases), withGeo)
}

// The adversarial guarantee, asserted directly: short keywords are word-bounded.
func TestShortKeywordsAreWordBounded(t *testing.T) {
	for _, title := range []string{"The wardrobe warehouse expands", "Something banned entirely"} {
		if got := ClassifyByKeyword(title, "full"); got.Level != "info" {
			t.Errorf("%q classified %s — a short keyword matched inside a longer word", title, got.Level)
		}
	}
}
