package world

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
)

// ── AI Analyst (agentic control surface) ─────────────────────────────────────
//
// /v1/world/analyst is a multi-turn chat grounded in a client-composed snapshot
// of the live dashboard. It is BOTH a Q&A analyst and the dashboard's control
// surface: the model may answer in prose AND/OR emit a small vocabulary of typed
// commands that the SPA executor maps 1:1 to app capabilities.
//
// The command vocabulary is NOT duplicated here. The client's command registry
// (src/services/app-commands.ts) is the single source of truth: the SPA sends its
// live manifest with every request, and this handler DERIVES the action contract
// in the system prompt from it (renderCommandContract). Callers that omit a
// manifest fall back to the embedded mirror (data/analyst_commands.json, generated
// from the same registry by scripts/gen-analyst-commands.mjs). The backend never
// re-validates params — it only passes structurally-valid, allow-typed actions
// through; the SPA dispatcher validates every field before it touches the app.
//
// Auth + billing: like every AI endpoint, it forwards the CALLER's IAM bearer to
// Hanzo inference (api.hanzo.ai) so usage meters to their org/project. No shared
// key. (hanzo.chat authenticates identically — forwarding the user's IAM token
// unchanged. World's token carries aud=hanzo-world; that audience must be on the
// gateway/cloud allowlist for the forward to be accepted — see the transport report.)

const analystMaxTurns = 12      // history cap (cost + context guard)
const analystMaxContent = 8000  // per-message content cap (abuse / OOM guard)
const analystContextCap = 12000 // client grounding-snapshot cap

// defaultCommandsJSON mirrors the client registry for callers that don't send a
// manifest. Generated by scripts/gen-analyst-commands.mjs; verified by test.
//
//go:embed data/analyst_commands.json
var defaultCommandsJSON []byte

// analystCommand is one entry of the command manifest (client-sent or embedded).
type analystCommand struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Params      analystParams `json:"params"`
	Authed      bool          `json:"authed"`
}

type analystParams struct {
	Type       string                 `json:"type"`
	Properties map[string]analystProp `json:"properties"`
	Required   []string               `json:"required"`
}

type analystProp struct {
	Type        string `json:"type"`
	Enum        []any  `json:"enum,omitempty"`
	Description string `json:"description,omitempty"`
}

// defaultCommands decodes the embedded fallback manifest.
func defaultCommands() []analystCommand {
	var cmds []analystCommand
	_ = json.Unmarshal(defaultCommandsJSON, &cmds)
	return cmds
}

// sanitizeCommands keeps well-formed, uniquely-named commands, preserving order.
func sanitizeCommands(in []analystCommand) []analystCommand {
	out := make([]analystCommand, 0, len(in))
	seen := map[string]bool{}
	for _, c := range in {
		name := strings.TrimSpace(c.Name)
		if name == "" || seen[name] || c.Params.Type != "object" {
			continue
		}
		seen[name] = true
		c.Name = name
		out = append(out, c)
	}
	return out
}

// handleAnalyst answers a multi-turn analyst conversation and, when the user asks
// for a change, returns typed commands for the SPA to execute.
func (s *Server) handleAnalyst(w http.ResponseWriter, r *http.Request) {
	if preflight(w, r, "POST, OPTIONS") {
		return
	}
	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "Method not allowed")
		return
	}
	var body struct {
		Messages []chatMessage    `json:"messages"`
		Context  string           `json:"context"`
		Commands []analystCommand `json:"commands"`
		Model    string           `json:"model"`
	}
	if err := decodeJSONBody(r, &body); err != nil {
		writeError(w, http.StatusBadRequest, "Invalid JSON body")
		return
	}
	msgs := sanitizeAnalystMessages(body.Messages)
	if len(msgs) == 0 {
		writeError(w, http.StatusBadRequest, "messages array required")
		return
	}

	// Per-user billing: forward the signed-in caller's IAM token, never a shared
	// key. Signed-out callers get a quiet prompt to sign in (never a 5xx).
	bearer := s.ai.bearerFor(r)
	if bearer == "" {
		writeJSON(w, http.StatusOK, "", map[string]any{
			"reply": "", "actions": []any{}, "fallback": true, "skipped": true,
			"reason": "Sign in to chat with the analyst",
		})
		return
	}

	// Command contract: client manifest is the source of truth; embedded mirror
	// is the fallback. The allowed-type set gates which actions pass through.
	cmds := sanitizeCommands(body.Commands)
	if len(cmds) == 0 {
		cmds = defaultCommands()
	}
	allowed := commandTypes(cmds)

	system := analystSystemPrompt(body.Context, renderCommandContract(cmds))
	// Time-scoped questions get grounded in the durable model history digest.
	if isTimeQuestion(latestUserContent(msgs)) {
		if digest := s.worldModel.HistoryDigest(24); digest != "" {
			system += "\n\n" + digest
		}
	}

	ctx, cancel := context.WithTimeout(r.Context(), 45*time.Second)
	defer cancel()

	model := sanitizeModel(body.Model)
	extra := aiForwardHeaders(r)

	// Agent path: a "agent:<ref>" model routes to the agents plane (invoke an
	// agent in-chat) instead of chat/completions. Prose result, same contract.
	if ref := agentRef(model); ref != "" {
		out, err := s.ai.runAgent(ctx, s, bearer, ref, latestUserContent(msgs), extra)
		if err != nil || out == "" {
			writeJSON(w, http.StatusOK, "", map[string]any{
				"reply": "", "actions": []any{}, "fallback": true, "model": model, "error": errStr(err),
			})
			return
		}
		reply, actions := parseAnalystOutput(out, allowed)
		writeJSON(w, http.StatusOK, "", map[string]any{"reply": reply, "actions": actions, "model": model})
		return
	}

	full := make([]chatMessage, 0, len(msgs)+1)
	full = append(full, chatMessage{Role: "system", Content: system})
	full = append(full, msgs...)

	out, tokens, err := s.ai.chatMessagesModel(ctx, s, bearer, model, full, 0.4, 700, extra)
	if err != nil || out == "" {
		// Surface the upstream reason honestly — the SPA renders it instead of a
		// blank chat (e.g. a 401 when aud=hanzo-world isn't allow-listed upstream).
		writeJSON(w, http.StatusOK, "", map[string]any{
			"reply": "", "actions": []any{}, "fallback": true, "error": errStr(err),
		})
		return
	}

	served := model
	if served == "" {
		served = s.ai.model
	}
	reply, actions := parseAnalystOutput(out, allowed)
	writeJSON(w, http.StatusOK, "", map[string]any{
		"reply": reply, "actions": actions, "model": served, "tokens": tokens,
	})
}

// ── Model / agent roster (drives the chat's model dropdown) ──────────────────

// zenRoster is the curated Zen family — always offered first so the dropdown
// works even before upstream /v1/models is reachable. Ids are the real served
// families (api.hanzo.ai). The default (ai.go model = "zen5") leads.
var zenRoster = []map[string]string{
	{"id": "zen5", "label": "Zen 5", "group": "Zen"},
	{"id": "zen5-flash", "label": "Zen 5 Flash", "group": "Zen"},
	{"id": "zen5-mini", "label": "Zen 5 Mini", "group": "Zen"},
	{"id": "zen5-pro", "label": "Zen 5 Pro", "group": "Zen"},
	{"id": "zen5-coder", "label": "Zen 5 Coder", "group": "Zen"},
	{"id": "zen3-omni", "label": "Zen 3 Omni", "group": "Zen"},
	{"id": "zen3-vl", "label": "Zen 3 VL", "group": "Zen"},
}

const rosterCap = 60

// handleModels returns the analyst model roster: the curated Zen family, then —
// best effort, for a signed-in caller — whatever the user can serve upstream
// (/v1/models) and any agents (/v1/agents). Never 5xx: no bearer or an upstream
// failure simply yields the curated list, so the dropdown always works.
func (s *Server) handleModels(w http.ResponseWriter, r *http.Request) {
	if preflight(w, r, "GET, OPTIONS") {
		return
	}
	if r.Method != http.MethodGet {
		writeError(w, http.StatusMethodNotAllowed, "Method not allowed")
		return
	}

	roster := make([]map[string]string, 0, rosterCap)
	seen := map[string]bool{}
	for _, m := range zenRoster {
		roster = append(roster, m)
		seen[m["id"]] = true
	}

	if bearer := s.ai.bearerFor(r); bearer != "" {
		ctx, cancel := context.WithTimeout(r.Context(), 8*time.Second)
		defer cancel()
		extra := aiForwardHeaders(r)
		for _, id := range s.ai.upstreamModels(ctx, s, bearer, extra) {
			if len(roster) >= rosterCap {
				break
			}
			if id != "" && !seen[id] {
				seen[id] = true
				roster = append(roster, map[string]string{"id": id, "label": id, "group": "Models"})
			}
		}
		for _, ag := range s.ai.upstreamAgents(ctx, s, bearer, extra) {
			if len(roster) >= rosterCap {
				break
			}
			id := "agent:" + ag.ref
			if ag.ref != "" && !seen[id] {
				seen[id] = true
				label := ag.name
				if label == "" {
					label = ag.ref
				}
				roster = append(roster, map[string]string{"id": id, "label": label, "group": "Agents"})
			}
		}
	}

	writeJSON(w, http.StatusOK, "no-store", map[string]any{"data": roster, "default": s.ai.model})
}

var modelIDRe = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,79}$`)

// sanitizeModel returns a syntactically-valid model id (or "" to use the default).
// A bad id upstream 4xxes into the degrade path, so we only guard the shape.
func sanitizeModel(m string) string {
	m = strings.TrimSpace(m)
	if modelIDRe.MatchString(m) {
		return m
	}
	return ""
}

// agentRef extracts the agent reference from a "agent:<ref>" model id, else "".
func agentRef(model string) string {
	if strings.HasPrefix(model, "agent:") {
		return strings.TrimSpace(strings.TrimPrefix(model, "agent:"))
	}
	return ""
}

// upstreamModels fetches servable model ids from api.hanzo.ai/v1/models (OpenAI
// shape). Any failure (incl. the aud-allowlist 401) yields nil — degrade quietly.
func (a *AIClient) upstreamModels(ctx context.Context, s *Server, bearer string, extra map[string]string) []string {
	headers := map[string]string{"Authorization": bearer}
	for k, v := range extra {
		headers[k] = v
	}
	body, status, err := s.do(ctx, "GET", a.base+"/models", headers, nil)
	if err != nil || status < 200 || status >= 300 {
		return nil
	}
	var parsed struct {
		Data []struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if json.Unmarshal(body, &parsed) != nil {
		return nil
	}
	ids := make([]string, 0, len(parsed.Data))
	for _, m := range parsed.Data {
		if id := strings.TrimSpace(m.ID); id != "" {
			ids = append(ids, id)
		}
	}
	return ids
}

type agentInfo struct{ ref, name string }

// upstreamAgents fetches the org's agents from api.hanzo.ai/v1/agents. The field
// names vary, so ref/name are read leniently. Any failure yields nil.
func (a *AIClient) upstreamAgents(ctx context.Context, s *Server, bearer string, extra map[string]string) []agentInfo {
	headers := map[string]string{"Authorization": bearer}
	for k, v := range extra {
		headers[k] = v
	}
	body, status, err := s.do(ctx, "GET", a.base+"/agents", headers, nil)
	if err != nil || status < 200 || status >= 300 {
		return nil
	}
	var parsed struct {
		Agents []map[string]any `json:"agents"`
		Data   []map[string]any `json:"data"`
	}
	if json.Unmarshal(body, &parsed) != nil {
		return nil
	}
	rows := parsed.Agents
	if len(rows) == 0 {
		rows = parsed.Data
	}
	out := make([]agentInfo, 0, len(rows))
	for _, m := range rows {
		ref := firstString(m, "ref", "id", "slug", "name")
		if ref == "" {
			continue
		}
		out = append(out, agentInfo{ref: ref, name: firstString(m, "name", "displayName", "title")})
	}
	return out
}

// runAgent invokes an agent in-chat via api.hanzo.ai/v1/agents/<ref>/run and
// returns its text output. Result shapes vary, so text is extracted leniently.
func (a *AIClient) runAgent(ctx context.Context, s *Server, bearer, ref, input string, extra map[string]string) (string, error) {
	reqBody, _ := json.Marshal(map[string]string{"input": input})
	headers := map[string]string{"Authorization": bearer, "Content-Type": "application/json"}
	for k, v := range extra {
		headers[k] = v
	}
	cctx, cancel := context.WithTimeout(ctx, 45*time.Second)
	defer cancel()
	body, status, err := s.do(cctx, "POST", a.base+"/agents/"+url.PathEscape(ref)+"/run", headers, reqBody)
	if err != nil {
		return "", err
	}
	if status < 200 || status >= 300 {
		return "", fmt.Errorf("hanzo agent status %d", status)
	}
	return extractAgentText(body), nil
}

// extractAgentText pulls the assistant text out of a variable agent-run result.
func extractAgentText(b []byte) string {
	var m map[string]any
	if json.Unmarshal(b, &m) != nil {
		return ""
	}
	for _, k := range []string{"output", "result", "reply", "text", "content", "answer", "message"} {
		if v, ok := m[k].(string); ok && strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
		if nested, ok := m[k].(map[string]any); ok {
			if t, ok := nested["text"].(string); ok && strings.TrimSpace(t) != "" {
				return strings.TrimSpace(t)
			}
			if t, ok := nested["content"].(string); ok && strings.TrimSpace(t) != "" {
				return strings.TrimSpace(t)
			}
		}
	}
	// OpenAI-ish {choices:[{message:{content}}]}
	if choices, ok := m["choices"].([]any); ok && len(choices) > 0 {
		if c0, ok := choices[0].(map[string]any); ok {
			if msg, ok := c0["message"].(map[string]any); ok {
				if t, ok := msg["content"].(string); ok {
					return strings.TrimSpace(t)
				}
			}
		}
	}
	return ""
}

func firstString(m map[string]any, keys ...string) string {
	for _, k := range keys {
		if v, ok := m[k].(string); ok && strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// ── Message + question helpers ───────────────────────────────────────────────

// sanitizeAnalystMessages validates roles, drops empties, caps content length,
// and keeps only the most recent analystMaxTurns turns.
func sanitizeAnalystMessages(in []chatMessage) []chatMessage {
	out := make([]chatMessage, 0, len(in))
	for _, m := range in {
		role := strings.ToLower(strings.TrimSpace(m.Role))
		if role != "user" && role != "assistant" {
			continue
		}
		content := strings.TrimSpace(m.Content)
		if content == "" {
			continue
		}
		if len(content) > analystMaxContent {
			content = content[:analystMaxContent]
		}
		out = append(out, chatMessage{Role: role, Content: content})
	}
	if len(out) > analystMaxTurns {
		out = out[len(out)-analystMaxTurns:]
	}
	return out
}

// latestUserContent returns the most recent user turn's text, or "".
func latestUserContent(msgs []chatMessage) string {
	for i := len(msgs) - 1; i >= 0; i-- {
		if msgs[i].Role == "user" {
			return msgs[i].Content
		}
	}
	return ""
}

// timeQuestionCues signal a time-scoped question — the only case worth the digest.
var timeQuestionCues = []string{
	"last ", "past ", "over the", "recent", "trend", "changed", "change",
	"since", "history", "24h", "24 hour", "48h", "hour", "yesterday",
	"today", "this week", "this month", "week", "day", "so far", "escalat",
	"evolv", "developing", "momentum", "trajectory",
}

// isTimeQuestion reports whether q reads as a question about change over time.
func isTimeQuestion(q string) bool {
	q = strings.ToLower(q)
	for _, cue := range timeQuestionCues {
		if strings.Contains(q, cue) {
			return true
		}
	}
	return false
}

// ── Prompt derivation (from the command manifest) ────────────────────────────

// commandTypes is the allow-set of command names the model may emit.
func commandTypes(cmds []analystCommand) map[string]bool {
	m := make(map[string]bool, len(cmds))
	for _, c := range cmds {
		if c.Name != "" {
			m[c.Name] = true
		}
	}
	return m
}

type fieldRef struct {
	name     string
	required bool
}

// orderedFields lists a command's params: required (declared order) then optional
// (sorted) — deterministic, so the rendered contract is stable.
func orderedFields(c analystCommand) []fieldRef {
	reqSet := map[string]bool{}
	out := make([]fieldRef, 0, len(c.Params.Properties))
	for _, r := range c.Params.Required {
		if _, ok := c.Params.Properties[r]; ok {
			out = append(out, fieldRef{r, true})
			reqSet[r] = true
		}
	}
	opt := make([]string, 0, len(c.Params.Properties))
	for k := range c.Params.Properties {
		if !reqSet[k] {
			opt = append(opt, k)
		}
	}
	sort.Strings(opt)
	for _, k := range opt {
		out = append(out, fieldRef{k, false})
	}
	return out
}

// renderField renders one param as it appears in the emitted JSON action, e.g.
// "range":"1h|6h|24h|48h|7d|all"  or  "zoom":<number>?  (? marks optional).
func renderField(name string, p analystProp, required bool) string {
	var val string
	switch {
	case len(p.Enum) > 0:
		parts := make([]string, 0, len(p.Enum))
		for _, e := range p.Enum {
			parts = append(parts, fmt.Sprint(e))
		}
		if p.Type == "string" {
			val = "\"" + strings.Join(parts, "|") + "\""
		} else {
			val = strings.Join(parts, "|")
		}
	case p.Type == "string":
		val = "\"<text>\""
	case p.Type == "number":
		val = "<number>"
	case p.Type == "integer":
		val = "<integer>"
	case p.Type == "boolean":
		val = "true|false"
	default:
		val = "<value>"
	}
	out := "\"" + name + "\":" + val
	if !required {
		out += "?"
	}
	return out
}

// renderCommandContract turns the manifest into the action-contract prompt block.
func renderCommandContract(cmds []analystCommand) string {
	var b strings.Builder
	for _, c := range cmds {
		b.WriteString("- {\"type\":\"" + c.Name + "\"")
		for _, f := range orderedFields(c) {
			b.WriteString("," + renderField(f.name, c.Params.Properties[f.name], f.required))
		}
		b.WriteString("}")
		if d := strings.TrimSpace(c.Description); d != "" {
			b.WriteString("  — " + d)
		}
		b.WriteByte('\n')
	}
	return b.String()
}

// analystSystemPrompt frames the analyst persona, grounds it in the client
// snapshot, and specifies the STRICT-JSON action contract derived from the
// command manifest (contract).
func analystSystemPrompt(snapshot, contract string) string {
	snapshot = strings.TrimSpace(snapshot)
	if len(snapshot) > analystContextCap {
		snapshot = snapshot[:analystContextCap]
	}
	ground := "No live dashboard snapshot was provided."
	if snapshot != "" {
		ground = "LIVE DASHBOARD SNAPSHOT (the user's current view — treat as ground truth):\n" + snapshot
	}

	return dateContext(false) + `

You are the Hanzo World analyst — an intelligence analyst embedded in a live
geopolitical/markets dashboard AND the dashboard's control surface. Answer the
user's questions grounded ONLY in the snapshot below and widely-known context; be
factual, concise, and specific. Do not invent numbers not present in the snapshot.

You can also RECONFIGURE the dashboard when the user asks for a change, by emitting
typed commands. Only emit commands when the user asks to change/rearrange/add/remove
something. For a plain question, reply in prose with NO commands.

Reply with STRICT JSON ONLY — no markdown, no code fences, no prose outside JSON:
{"reply": "<your message to the user>", "actions": [ <zero or more commands> ]}

Available commands (use panel/layer/org keys EXACTLY as they appear in the snapshot;
a trailing ? marks an optional field):
` + strings.TrimRight(contract, "\n") + `

Rules:
- Prefer the fewest commands that satisfy the request. Reference panels by their
  names in "reply" (e.g. "moved Live News to the top"), but use their keys in the command.
- add_feed_panel only works for domains on the server RSS allowlist. If unsure, still
  emit it — the executor validates it and reports if the domain is blocked. Never try
  to bypass it.
- Never emit a command type not listed above. Unknown or unsupported requests: explain
  briefly in "reply" with no command.
- "reply" is always present, even when there are commands (say what you changed).

` + ground
}

// parseAnalystOutput extracts {reply, actions} from the model output. Actions are
// passed through as generic objects (the SPA validates every field); only actions
// whose "type" is in the allow-set survive. If nothing parses, the whole output is
// the reply with no actions (safe degrade — a chat answer is never lost).
func parseAnalystOutput(raw string, allowed map[string]bool) (string, []map[string]any) {
	obj := extractJSONObject(raw)
	if obj == "" {
		return strings.TrimSpace(raw), nil
	}
	var parsed struct {
		Reply   string           `json:"reply"`
		Actions []map[string]any `json:"actions"`
	}
	if err := json.Unmarshal([]byte(obj), &parsed); err != nil {
		return strings.TrimSpace(raw), nil
	}
	actions := make([]map[string]any, 0, len(parsed.Actions))
	for _, a := range parsed.Actions {
		t, _ := a["type"].(string)
		t = strings.ToLower(strings.TrimSpace(t))
		if t == "" || !allowed[t] {
			continue
		}
		a["type"] = t
		actions = append(actions, a)
	}
	reply := strings.TrimSpace(parsed.Reply)
	if reply == "" && len(actions) == 0 {
		return strings.TrimSpace(raw), nil
	}
	return reply, actions
}

// extractJSONObject returns the outermost {...} span in s (fence/prose tolerant),
// or "" if none is balanced.
func extractJSONObject(s string) string {
	start := strings.Index(s, "{")
	if start < 0 {
		return ""
	}
	depth, inStr, esc := 0, false, false
	for i := start; i < len(s); i++ {
		c := s[i]
		switch {
		case esc:
			esc = false
		case c == '\\' && inStr:
			esc = true
		case c == '"':
			inStr = !inStr
		case inStr:
			// skip
		case c == '{':
			depth++
		case c == '}':
			depth--
			if depth == 0 {
				return s[start : i+1]
			}
		}
	}
	return ""
}
